callModule(server.modules_pancan_dist, "module_gene_pancan_dist")
callModule(server.modules_sur_plot, "modules_sur_plot")
callModule(server.file_upload, "module_file_upload")
callModule(server.modules_pancan_unicox, "modules_pancan_unicox")
callModule(server.modules_pancan_anatomy, "modules_pancan_anatomy")